version: "2"
services:
  client:
    build:
      context: client
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm start
    ports:
      - "4200:4200"
    links:
      - api
  api:
    build:
      context: api
      dockerfile: Dockerfile
    command: bin/rails server --port 3000 --binding 0.0.0.0
    volumes:
      - ./api:/api
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    links:
      - postgres
  postgres:
    image: postgres:9.6
    environment:
      - PGUSER=postgres
      - PGDATABASE=api
      - PGHOST=postgres
    ports:
      - "5432:5432"
volumes:
  bundle:
  node_modules:


